// const List<Map<String, String>> codes = [
//   {"name": "افغانستان", "code": "AF", "iso3Code": "AFG", "dial_code": "+93"},
//   {"name": "Åland", "code": "AX", "iso3Code": "ALA", "dial_code": "+358"},
//   {"name": "Shqipëria", "code": "AL", "iso3Code": "ALB", "dial_code": "+355"},
//   {"name": "الجزائر", "code": "DZ", "iso3Code": "DZA", "dial_code": "+213"},
//   {
//     "name": "American Samoa",
//     "code": "AS",
//     "iso3Code": "ASM",
//     "dial_code": "+1684"
//   },
//   {"name": "Andorra", "code": "AD", "iso3Code": "AND", "dial_code": "+376"},
//   {"name": "Angola", "code": "AO", "iso3Code": "AGO", "dial_code": "+244"},
//   {"name": "Anguilla", "code": "AI", "iso3Code": "AIA", "dial_code": "+1264"},
//   {"name": "Antarctica", "code": "AQ", "iso3Code": "ATA", "dial_code": "+672"},
//   {
//     "name": "Antigua and Barbuda",
//     "code": "AG",
//     "iso3Code": "ATG",
//     "dial_code": "+1268"
//   },
//   {"name": "Argentina", "code": "AR", "iso3Code": "ARG", "dial_code": "+54"},
//   {"name": "Հայաստան", "code": "AM", "iso3Code": "ARM", "dial_code": "+374"},
//   {"name": "Aruba", "code": "AW", "iso3Code": "ABW", "dial_code": "+297"},
//   {"name": "Australia", "code": "AU", "iso3Code": "AUS", "dial_code": "+61"},
//   {"name": "Österreich", "code": "AT", "iso3Code": "AUT", "dial_code": "+43"},
//   {"name": "Azərbaycan", "code": "AZ", "iso3Code": "AZE", "dial_code": "+994"},
//   {"name": "Bahamas", "code": "BS", "iso3Code": "BHS", "dial_code": "+1242"},
//   {"name": "‏البحرين", "code": "BH", "iso3Code": "BHR", "dial_code": "+973"},
//   {"name": "Bangladesh", "code": "BD", "iso3Code": "BGD", "dial_code": "+880"},
//   {"name": "Barbados", "code": "BB", "iso3Code": "BRB", "dial_code": "+1246"},
//   {"name": "Белару́сь", "code": "BY", "iso3Code": "BLR", "dial_code": "+375"},
//   {"name": "België", "code": "BE", "iso3Code": "BEL", "dial_code": "+32"},
//   {"name": "Belize", "code": "BZ", "iso3Code": "BLZ", "dial_code": "+501"},
//   {"name": "Bénin", "code": "BJ", "iso3Code": "BEN", "dial_code": "+229"},
//   {"name": "Bermuda", "code": "BM", "iso3Code": "BMU", "dial_code": "+1441"},
//   {"name": "ʼbrug-yul", "code": "BT", "iso3Code": "BTN", "dial_code": "+975"},
//   {"name": "Bolivia", "code": "BO", "iso3Code": "BOL", "dial_code": "+591"},
//   {
//     "name": "Bosna i Hercegovina",
//     "code": "BA",
//     "iso3Code": "BIH",
//     "dial_code": "+387"
//   },
//   {"name": "Botswana", "code": "BW", "iso3Code": "BWA", "dial_code": "+267"},
//   {"name": "Bouvetøya", "code": "BV", "iso3Code": "BVT", "dial_code": "+47"},
//   {"name": "Brasil", "code": "BR", "iso3Code": "BRA", "dial_code": "+55"},
//   {
//     "name": "British Indian Ocean Territory",
//     "code": "IO",
//     "iso3Code": "IOT",
//     "dial_code": "+246"
//   },
//   {
//     "name": "Negara Brunei Darussalam",
//     "code": "BN",
//     "iso3Code": "BRN",
//     "dial_code": "+673"
//   },
//   {"name": "България", "code": "BG", "iso3Code": "BGR", "dial_code": "+359"},
//   {
//     "name": "Burkina Faso",
//     "code": "BF",
//     "iso3Code": "BFA",
//     "dial_code": "+226"
//   },
//   {"name": "Burundi", "code": "BI", "iso3Code": "BDI", "dial_code": "+257"},
//   {"name": "Cambodia", "code": "KH", "iso3Code": "KHM", "dial_code": "+855"},
//   {"name": "Cameroon", "code": "CM", "iso3Code": "CMR", "dial_code": "+237"},
//   {"name": "Canada", "code": "CA", "iso3Code": "CAN", "dial_code": "+1"},
//   {"name": "Cabo Verde", "code": "CV", "iso3Code": "CPV", "dial_code": "+238"},
//   {
//     "name": "Cayman Islands",
//     "code": "KY",
//     "iso3Code": "CYM",
//     "dial_code": "+1345"
//   },
//   {
//     "name": "Ködörösêse tî Bêafrîka",
//     "code": "CF",
//     "iso3Code": "CAF",
//     "dial_code": "+236"
//   },
//   {"name": "Tchad", "code": "TD", "iso3Code": "TCD", "dial_code": "+235"},
//   {"name": "Chile", "code": "CL", "iso3Code": "CHL", "dial_code": "+56"},
//   {"name": "中国", "code": "CN", "iso3Code": "CHN", "dial_code": "+86"},
//   {
//     "name": "Christmas Island",
//     "code": "CX",
//     "iso3Code": "CXR",
//     "dial_code": "+61"
//   },
//   {
//     "name": "Cocos (Keeling) Islands",
//     "code": "CC",
//     "iso3Code": "CCK",
//     "dial_code": "+61"
//   },
//   {"name": "Colombia", "code": "CO", "iso3Code": "COL", "dial_code": "+57"},
//   {"name": "Komori", "code": "KM", "iso3Code": "COM", "dial_code": "+269"},
//   {
//     "name": "République du Congo",
//     "code": "CG",
//     "iso3Code": "COG",
//     "dial_code": "+242"
//   },
//   {
//     "name": "République démocratique du Congo",
//     "code": "CD",
//     "iso3Code": "COD",
//     "dial_code": "+243"
//   },
//   {
//     "name": "Cook Islands",
//     "code": "CK",
//     "iso3Code": "COK",
//     "dial_code": "+682"
//   },
//   {"name": "Costa Rica", "code": "CR", "iso3Code": "CRI", "dial_code": "+506"},
//   {
//     "name": "Côte d'Ivoire",
//     "code": "CI",
//     "iso3Code": "CIV",
//     "dial_code": "+225"
//   },
//   {"name": "Hrvatska", "code": "HR", "iso3Code": "HRV", "dial_code": "+385"},
//   {"name": "Cuba", "code": "CU", "iso3Code": "CUB", "dial_code": "+53"},
//   {"name": "Κύπρος", "code": "CY", "iso3Code": "CYP", "dial_code": "+357"},
//   {
//     "name": "Česká republika",
//     "code": "CZ",
//     "iso3Code": "CZE",
//     "dial_code": "+420"
//   },
//   {"name": "Danmark", "code": "DK", "iso3Code": "DNK", "dial_code": "+45"},
//   {"name": "Djibouti", "code": "DJ", "iso3Code": "DJI", "dial_code": "+253"},
//   {"name": "Dominica", "code": "DM", "iso3Code": "DMA", "dial_code": "+1767"},
//   {
//     "name": "República Dominicana",
//     "code": "DO",
//     "iso3Code": "DOM",
//     "dial_code": "+1"
//   },
//   {"name": "Ecuador", "code": "EC", "iso3Code": "ECU", "dial_code": "+593"},
//   {"name": "مصر‎", "code": "EG", "iso3Code": "EGY", "dial_code": "+20"},
//   {"name": "El Salvador", "code": "SV", "iso3Code": "SLV", "dial_code": "+503"},
//   {
//     "name": "Guinea Ecuatorial",
//     "code": "GQ",
//     "iso3Code": "GNQ",
//     "dial_code": "+240"
//   },
//   {"name": "ኤርትራ", "code": "ER", "iso3Code": "ERI", "dial_code": "+291"},
//   {"name": "Eesti", "code": "EE", "iso3Code": "EST", "dial_code": "+372"},
//   {"name": "ኢትዮጵያ", "code": "ET", "iso3Code": "ETH", "dial_code": "+251"},
//   {
//     "name": "Falkland Islands",
//     "code": "FK",
//     "iso3Code": "FLK",
//     "dial_code": "+500"
//   },
//   {"name": "Føroyar", "code": "FO", "iso3Code": "FRO", "dial_code": "+298"},
//   {"name": "Fiji", "code": "FJ", "iso3Code": "FJI", "dial_code": "+679"},
//   {"name": "Suomi", "code": "FI", "iso3Code": "FIN", "dial_code": "+358"},
//   {"name": "France", "code": "FR", "iso3Code": "FRA", "dial_code": "+33"},
//   {
//     "name": "Guyane française",
//     "code": "GF",
//     "iso3Code": "GUF",
//     "dial_code": "+594"
//   },
//   {
//     "name": "Polynésie française",
//     "code": "PF",
//     "iso3Code": "PYF",
//     "dial_code": "+689"
//   },
//   {
//     "name": "Territoire des Terres australes et antarctiques fr",
//     "code": "TF",
//     "iso3Code": "ATF",
//     "dial_code": "+262"
//   },
//   {"name": "Gabon", "code": "GA", "iso3Code": "GAB", "dial_code": "+241"},
//   {"name": "Gambia", "code": "GM", "iso3Code": "GMB", "dial_code": "+220"},
//   {"name": "საქართველო", "code": "GE", "iso3Code": "GEO", "dial_code": "+995"},
//   {"name": "Deutschland", "code": "DE", "iso3Code": "DEU", "dial_code": "+49"},
//   {"name": "Ghana", "code": "GH", "iso3Code": "GHA", "dial_code": "+233"},
//   {"name": "Gibraltar", "code": "GI", "iso3Code": "GIB", "dial_code": "+350"},
//   {"name": "Ελλάδα", "code": "GR", "iso3Code": "GRC", "dial_code": "+30"},
//   {
//     "name": "Kalaallit Nunaat",
//     "code": "GL",
//     "iso3Code": "GRL",
//     "dial_code": "+299"
//   },
//   {"name": "Grenada", "code": "GD", "iso3Code": "GRD", "dial_code": "+1473"},
//   {"name": "Guadeloupe", "code": "GP", "iso3Code": "GLP", "dial_code": "+590"},
//   {"name": "Guam", "code": "GU", "iso3Code": "GUM", "dial_code": "+1671"},
//   {"name": "Guatemala", "code": "GT", "iso3Code": "GTM", "dial_code": "+502"},
//   {"name": "Guernsey", "code": "GG", "iso3Code": "GGY", "dial_code": "+44"},
//   {"name": "Guinée", "code": "GN", "iso3Code": "GIN", "dial_code": "+224"},
//   {
//     "name": "Guiné-Bissau",
//     "code": "GW",
//     "iso3Code": "GNB",
//     "dial_code": "+245"
//   },
//   {"name": "Guyana", "code": "GY", "iso3Code": "GUY", "dial_code": "+592"},
//   {"name": "Haïti", "code": "HT", "iso3Code": "HTI", "dial_code": "+509"},
//   {
//     "name": "Heard Island and McDonald Islands",
//     "code": "HM",
//     "iso3Code": "HMD",
//     "dial_code": "+0"
//   },
//   {"name": "Vaticano", "code": "VA", "iso3Code": "VAT", "dial_code": "+379"},
//   {"name": "Honduras", "code": "HN", "iso3Code": "HND", "dial_code": "+504"},
//   {"name": "香港", "code": "HK", "iso3Code": "HKG", "dial_code": "+852"},
//   {"name": "Magyarország", "code": "HU", "iso3Code": "HUN", "dial_code": "+36"},
//   {"name": "Ísland", "code": "IS", "iso3Code": "ISL", "dial_code": "+354"},
//   {"name": "भारत", "code": "IN", "iso3Code": "IND", "dial_code": "+91"},
//   {"name": "Indonesia", "code": "ID", "iso3Code": "IDN", "dial_code": "+62"},
//   {"name": "ایران", "code": "IR", "iso3Code": "IRN", "dial_code": "+98"},
//   {"name": "العراق", "code": "IQ", "iso3Code": "IRQ", "dial_code": "+964"},
//   {"name": "Éire", "code": "IE", "iso3Code": "IRL", "dial_code": "+353"},
//   {"name": "Isle of Man", "code": "IM", "iso3Code": "IMN", "dial_code": "+44"},
//   {"name": "ישראל", "code": "IL", "iso3Code": "ISR", "dial_code": "+972"},
//   {"name": "Italia", "code": "IT", "iso3Code": "ITA", "dial_code": "+39"},
//   {"name": "Jamaica", "code": "JM", "iso3Code": "JAM", "dial_code": "+1876"},
//   {"name": "日本", "code": "JP", "iso3Code": "JPN", "dial_code": "+81"},
//   {"name": "Jersey", "code": "JE", "iso3Code": "JEY", "dial_code": "+44"},
//   {"name": "الأردن", "code": "JO", "iso3Code": "JOR", "dial_code": "+962"},
//   {"name": "Қазақстан", "code": "KZ", "iso3Code": "KAZ", "dial_code": "+7"},
//   {"name": "Kenya", "code": "KE", "iso3Code": "KEN", "dial_code": "+254"},
//   {"name": "Kiribati", "code": "KI", "iso3Code": "KIR", "dial_code": "+686"},
//   {"name": "북한", "code": "KP", "iso3Code": "PRK", "dial_code": "+850"},
//   {"name": "대한민국", "code": "KR", "iso3Code": "KOR", "dial_code": "+82"},
//   {
//     "name": "Republika e Kosovës",
//     "code": "XK",
//     "iso3Code": "KOS",
//     "dial_code": "+383"
//   },
//   {"name": "الكويت", "code": "KW", "iso3Code": "KWT", "dial_code": "+965"},
//   {"name": "Кыргызстан", "code": "KG", "iso3Code": "KGZ", "dial_code": "+996"},
//   {"name": "ສປປລາວ", "code": "LA", "iso3Code": "LAO", "dial_code": "+856"},
//   {"name": "Latvija", "code": "LV", "iso3Code": "LVA", "dial_code": "+371"},
//   {"name": "لبنان", "code": "LB", "iso3Code": "LBN", "dial_code": "+961"},
//   {"name": "Lesotho", "code": "LS", "iso3Code": "LSO", "dial_code": "+266"},
//   {"name": "Liberia", "code": "LR", "iso3Code": "LBR", "dial_code": "+231"},
//   {"name": "‏ليبيا", "code": "LY", "iso3Code": "LBY", "dial_code": "+218"},
//   {
//     "name": "Liechtenstein",
//     "code": "LI",
//     "iso3Code": "LIE",
//     "dial_code": "+423"
//   },
//   {"name": "Lietuva", "code": "LT", "iso3Code": "LTU", "dial_code": "+370"},
//   {"name": "Luxembourg", "code": "LU", "iso3Code": "LUX", "dial_code": "+352"},
//   {"name": "澳門", "code": "MO", "iso3Code": "MAC", "dial_code": "+853"},
//   {"name": "Македонија", "code": "MK", "iso3Code": "MKD", "dial_code": "+389"},
//   {
//     "name": "Madagasikara",
//     "code": "MG",
//     "iso3Code": "MDG",
//     "dial_code": "+261"
//   },
//   {"name": "Malawi", "code": "MW", "iso3Code": "MWI", "dial_code": "+265"},
//   {"name": "Malaysia", "code": "MY", "iso3Code": "MYS", "dial_code": "+60"},
//   {"name": "Maldives", "code": "MV", "iso3Code": "MDV", "dial_code": "+960"},
//   {"name": "Mali", "code": "ML", "iso3Code": "MLI", "dial_code": "+223"},
//   {"name": "Malta", "code": "MT", "iso3Code": "MLT", "dial_code": "+356"},
//   {"name": "M̧ajeļ", "code": "MH", "iso3Code": "MHL", "dial_code": "+692"},
//   {"name": "Martinique", "code": "MQ", "iso3Code": "MTQ", "dial_code": "+596"},
//   {"name": "موريتانيا", "code": "MR", "iso3Code": "MRT", "dial_code": "+222"},
//   {"name": "Maurice", "code": "MU", "iso3Code": "MUS", "dial_code": "+230"},
//   {"name": "Mayotte", "code": "YT", "iso3Code": "MYT", "dial_code": "+262"},
//   {"name": "México", "code": "MX", "iso3Code": "MEX", "dial_code": "+52"},
//   {"name": "Micronesia", "code": "FM", "iso3Code": "FSM", "dial_code": "+691"},
//   {"name": "Moldova", "code": "MD", "iso3Code": "MDA", "dial_code": "+373"},
//   {"name": "Monaco", "code": "MC", "iso3Code": "MCO", "dial_code": "+377"},
//   {"name": "Монгол улс", "code": "MN", "iso3Code": "MNG", "dial_code": "+976"},
//   {"name": "Црна Гора", "code": "ME", "iso3Code": "MNE", "dial_code": "+382"},
//   {"name": "Montserrat", "code": "MS", "iso3Code": "MSR", "dial_code": "+1664"},
//   {"name": "المغرب", "code": "MA", "iso3Code": "MAR", "dial_code": "+212"},
//   {"name": "Moçambique", "code": "MZ", "iso3Code": "MOZ", "dial_code": "+258"},
//   {"name": "Myanmar", "code": "MM", "iso3Code": "MMR", "dial_code": "+95"},
//   {"name": "Namibia", "code": "NA", "iso3Code": "NAM", "dial_code": "+264"},
//   {"name": "Nauru", "code": "NR", "iso3Code": "NRU", "dial_code": "+674"},
//   {"name": "नेपाल", "code": "NP", "iso3Code": "NPL", "dial_code": "+977"},
//   {"name": "Nederland", "code": "NL", "iso3Code": "NLD", "dial_code": "+31"},
//   {
//     "name": "Netherlands Antilles",
//     "code": "AN",
//     "iso3Code": "AN",
//     "dial_code": "+599"
//   },
//   {
//     "name": "Nouvelle-Calédonie",
//     "code": "NC",
//     "iso3Code": "NCL",
//     "dial_code": "+687"
//   },
//   {"name": "New Zealand", "code": "NZ", "iso3Code": "NZL", "dial_code": "+64"},
//   {"name": "Nicaragua", "code": "NI", "iso3Code": "NIC", "dial_code": "+505"},
//   {"name": "Niger", "code": "NE", "iso3Code": "NER", "dial_code": "+227"},
//   {"name": "Nigeria", "code": "NG", "iso3Code": "NGA", "dial_code": "+234"},
//   {"name": "Niuē", "code": "NU", "iso3Code": "NIU", "dial_code": "+683"},
//   {
//     "name": "Norfolk Island",
//     "code": "NF",
//     "iso3Code": "NFK",
//     "dial_code": "+672"
//   },
//   {
//     "name": "Northern Mariana Islands",
//     "code": "MP",
//     "iso3Code": "MNP",
//     "dial_code": "+1670"
//   },
//   {"name": "Norge", "code": "NO", "iso3Code": "NOR", "dial_code": "+47"},
//   {"name": "عمان", "code": "OM", "iso3Code": "OMN", "dial_code": "+968"},
//   {"name": "Pakistan", "code": "PK", "iso3Code": "PAK", "dial_code": "+92"},
//   {"name": "Palau", "code": "PW", "iso3Code": "PLW", "dial_code": "+680"},
//   {"name": "فلسطين", "code": "PS", "iso3Code": "PSE", "dial_code": "+970"},
//   {"name": "Panamá", "code": "PA", "iso3Code": "PAN", "dial_code": "+507"},
//   {
//     "name": "Papua Niugini",
//     "code": "PG",
//     "iso3Code": "PNG",
//     "dial_code": "+675"
//   },
//   {"name": "Paraguay", "code": "PY", "iso3Code": "PRY", "dial_code": "+595"},
//   {"name": "Perú", "code": "PE", "iso3Code": "PER", "dial_code": "+51"},
//   {"name": "Pilipinas", "code": "PH", "iso3Code": "PHL", "dial_code": "+63"},
//   {
//     "name": "Pitcairn Islands",
//     "code": "PN",
//     "iso3Code": "PCN",
//     "dial_code": "+64"
//   },
//   {"name": "Polska", "code": "PL", "iso3Code": "POL", "dial_code": "+48"},
//   {"name": "Portugal", "code": "PT", "iso3Code": "PRT", "dial_code": "+351"},
//   {
//     "name": "Puerto Rico",
//     "code": "PR",
//     "iso3Code": "PRI",
//     "dial_code": "+1939"
//   },
//   {
//     "name": "Puerto Rico",
//     "code": "PR",
//     "iso3Code": "PRI",
//     "dial_code": "+1787"
//   },
//   {"name": "قطر", "code": "QA", "iso3Code": "QAT", "dial_code": "+974"},
//   {"name": "România", "code": "RO", "iso3Code": "ROU", "dial_code": "+40"},
//   {"name": "Россия", "code": "RU", "iso3Code": "RUS", "dial_code": "+7"},
//   {"name": "Rwanda", "code": "RW", "iso3Code": "RWA", "dial_code": "+250"},
//   {"name": "La Réunion", "code": "RE", "iso3Code": "REU", "dial_code": "+262"},
//   {
//     "name": "Saint-Barthélemy",
//     "code": "BL",
//     "iso3Code": "BLM",
//     "dial_code": "+590"
//   },
//   {
//     "name": "Saint Helena",
//     "code": "SH",
//     "iso3Code": "SHN",
//     "dial_code": "+290"
//   },
//   {
//     "name": "Saint Kitts and Nevis",
//     "code": "KN",
//     "iso3Code": "KNA",
//     "dial_code": "+1869"
//   },
//   {
//     "name": "Saint Lucia",
//     "code": "LC",
//     "iso3Code": "LCA",
//     "dial_code": "+1758"
//   },
//   {
//     "name": "Saint-Martin",
//     "code": "MF",
//     "iso3Code": "MAF",
//     "dial_code": "+590"
//   },
//   {
//     "name": "Saint-Pierre-et-Miquelon",
//     "code": "PM",
//     "iso3Code": "SPM",
//     "dial_code": "+508"
//   },
//   {
//     "name": "Saint Vincent and the Grenadines",
//     "code": "VC",
//     "iso3Code": "VCT",
//     "dial_code": "+1784"
//   },
//   {"name": "Samoa", "code": "WS", "iso3Code": "WSM", "dial_code": "+685"},
//   {"name": "San Marino", "code": "SM", "iso3Code": "SMR", "dial_code": "+378"},
//   {
//     "name": "São Tomé e Príncipe",
//     "code": "ST",
//     "iso3Code": "STP",
//     "dial_code": "+239"
//   },
//   {
//     "name": "العربية السعودية",
//     "code": "SA",
//     "iso3Code": "SAU",
//     "dial_code": "+966"
//   },
//   {"name": "Sénégal", "code": "SN", "iso3Code": "SEN", "dial_code": "+221"},
//   {"name": "Србија", "code": "RS", "iso3Code": "SRB", "dial_code": "+381"},
//   {"name": "Seychelles", "code": "SC", "iso3Code": "SYC", "dial_code": "+248"},
//   {
//     "name": "Sierra Leone",
//     "code": "SL",
//     "iso3Code": "SLE",
//     "dial_code": "+232"
//   },
//   {"name": "Singapore", "code": "SG", "iso3Code": "SGP", "dial_code": "+65"},
//   {"name": "Slovensko", "code": "SK", "iso3Code": "SVK", "dial_code": "+421"},
//   {"name": "Slovenija", "code": "SI", "iso3Code": "SVN", "dial_code": "+386"},
//   {
//     "name": "Solomon Islands",
//     "code": "SB",
//     "iso3Code": "SLB",
//     "dial_code": "+677"
//   },
//   {"name": "Soomaaliya", "code": "SO", "iso3Code": "SOM", "dial_code": "+252"},
//   {"name": "South Africa", "code": "ZA", "iso3Code": "ZAF", "dial_code": "+27"},
//   {"name": "South Sudan", "code": "SS", "iso3Code": "SSD", "dial_code": "+211"},
//   {
//     "name": "South Georgia",
//     "code": "GS",
//     "iso3Code": "SGS",
//     "dial_code": "+500"
//   },
//   {"name": "España", "code": "ES", "iso3Code": "ESP", "dial_code": "+34"},
//   {"name": "Sri Lanka", "code": "LK", "iso3Code": "LKA", "dial_code": "+94"},
//   {"name": "السودان", "code": "SD", "iso3Code": "SDN", "dial_code": "+249"},
//   {"name": "Suriname", "code": "SR", "iso3Code": "SUR", "dial_code": "+597"},
//   {
//     "name": "Svalbard og Jan Mayen",
//     "code": "SJ",
//     "iso3Code": "SJM",
//     "dial_code": "+47"
//   },
//   {"name": "Swaziland", "code": "SZ", "iso3Code": "SWZ", "dial_code": "+268"},
//   {"name": "Sverige", "code": "SE", "iso3Code": "SWE", "dial_code": "+46"},
//   {"name": "Schweiz", "code": "CH", "iso3Code": "CHE", "dial_code": "+41"},
//   {"name": "سوريا", "code": "SY", "iso3Code": "SYR", "dial_code": "+963"},
//   {"name": "臺灣", "code": "TW", "iso3Code": "TWN", "dial_code": "+886"},
//   {"name": "Тоҷикистон", "code": "TJ", "iso3Code": "TJK", "dial_code": "+992"},
//   {"name": "Tanzania", "code": "TZ", "iso3Code": "TZA", "dial_code": "+255"},
//   {"name": "ประเทศไทย", "code": "TH", "iso3Code": "THA", "dial_code": "+66"},
//   {"name": "Timor-Leste", "code": "TL", "iso3Code": "TLS", "dial_code": "+670"},
//   {"name": "Togo", "code": "TG", "iso3Code": "TGO", "dial_code": "+228"},
//   {"name": "Tokelau", "code": "TK", "iso3Code": "TKL", "dial_code": "+690"},
//   {"name": "Tonga", "code": "TO", "iso3Code": "TON", "dial_code": "+676"},
//   {
//     "name": "Trinidad and Tobago",
//     "code": "TT",
//     "iso3Code": "TTO",
//     "dial_code": "+1868"
//   },
//   {"name": "تونس", "code": "TN", "iso3Code": "TUN", "dial_code": "+216"},
//   {"name": "Türkiye", "code": "TR", "iso3Code": "TUR", "dial_code": "+90"},
//   {
//     "name": "Türkmenistan",
//     "code": "TM",
//     "iso3Code": "TKM",
//     "dial_code": "+993"
//   },
//   {
//     "name": "Turks and Caicos Islands",
//     "code": "TC",
//     "iso3Code": "TCA",
//     "dial_code": "+1649"
//   },
//   {"name": "Tuvalu", "code": "TV", "iso3Code": "TUV", "dial_code": "+688"},
//   {"name": "Uganda", "code": "UG", "iso3Code": "UGA", "dial_code": "+256"},
//   {"name": "Україна", "code": "UA", "iso3Code": "UKR", "dial_code": "+380"},
//   {
//     "name": "دولة الإمارات العربية المتحدة",
//     "code": "AE",
//     "iso3Code": "ARE",
//     "dial_code": "+971"
//   },
//   {
//     "name": "United Kingdom",
//     "code": "GB",
//     "iso3Code": "GBR",
//     "dial_code": "+44"
//   },
//   {"name": "United States", "code": "US", "iso3Code": "USA", "dial_code": "+1"},
//   {"name": "Uruguay", "code": "UY", "iso3Code": "URY", "dial_code": "+598"},
//   {"name": "O‘zbekiston", "code": "UZ", "iso3Code": "UZB", "dial_code": "+998"},
//   {"name": "Vanuatu", "code": "VU", "iso3Code": "VUT", "dial_code": "+678"},
//   {"name": "Venezuela", "code": "VE", "iso3Code": "VEN", "dial_code": "+58"},
//   {"name": "Việt Nam", "code": "VN", "iso3Code": "VNM", "dial_code": "+84"},
//   {
//     "name": "British Virgin Islands",
//     "code": "VG",
//     "iso3Code": "VGB",
//     "dial_code": "+1284"
//   },
//   {
//     "name": "United States Virgin Islands",
//     "code": "VI",
//     "iso3Code": "VIR",
//     "dial_code": "+1340"
//   },
//   {
//     "name": "Wallis et Futuna",
//     "code": "WF",
//     "iso3Code": "WLF",
//     "dial_code": "+681"
//   },
//   {"name": "اليَمَن", "code": "YE", "iso3Code": "YEM", "dial_code": "+967"},
//   {"name": "Zambia", "code": "ZM", "iso3Code": "ZMB", "dial_code": "+260"},
//   {"name": "Zimbabwe", "code": "ZW", "iso3Code": "ZWE", "dial_code": "+263"}
// ];

const List<Map<String, String>> codes = [
  {"name": "افغانستان", "code": "AF", "iso3Code": "AFG", "dial_code": "+93", "minLength": "9", "maxLength": "9"},
  {"name": "Åland", "code": "AX", "iso3Code": "ALA", "dial_code": "+358", "minLength": "15", "maxLength": "15"},
  {"name": "Shqipëria", "code": "AL", "iso3Code": "ALB", "dial_code": "+355", "minLength": "9", "maxLength": "9"},
  {"name": "الجزائر", "code": "DZ", "iso3Code": "DZA", "dial_code": "+213", "minLength": "9", "maxLength": "9"},
  {"name": "American Samoa", "code": "AS", "iso3Code": "ASM", "dial_code": "+1684", "minLength": "7", "maxLength": "7"},
  {"name": "Andorra", "code": "AD", "iso3Code": "AND", "dial_code": "+376", "minLength": "6", "maxLength": "6"},
  {"name": "Angola", "code": "AO", "iso3Code": "AGO", "dial_code": "+244", "minLength": "9", "maxLength": "9"},
  {"name": "Anguilla", "code": "AI", "iso3Code": "AIA", "dial_code": "+1264", "minLength": "7", "maxLength": "7"},
  {"name": "Antarctica", "code": "AQ", "iso3Code": "ATA", "dial_code": "+672", "minLength": "6", "maxLength": "6"},
  {
    "name": "Antigua and Barbuda",
    "code": "AG",
    "iso3Code": "ATG",
    "dial_code": "+1268",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "Argentina", "code": "AR", "iso3Code": "ARG", "dial_code": "+54", "minLength": "12", "maxLength": "12"},
  {"name": "Հայաստան", "code": "AM", "iso3Code": "ARM", "dial_code": "+374", "minLength": "8", "maxLength": "8"},
  {"name": "Aruba", "code": "AW", "iso3Code": "ABW", "dial_code": "+297", "minLength": "7", "maxLength": "7"},
  {"name": "Australia", "code": "AU", "iso3Code": "AUS", "dial_code": "+61", "minLength": "9", "maxLength": "9"},
  {"name": "Österreich", "code": "AT", "iso3Code": "AUT", "dial_code": "+43", "minLength": "13", "maxLength": "13"},
  {"name": "Azərbaycan", "code": "AZ", "iso3Code": "AZE", "dial_code": "+994", "minLength": "9", "maxLength": "9"},
  {"name": "Bahamas", "code": "BS", "iso3Code": "BHS", "dial_code": "+1242", "minLength": "7", "maxLength": "7"},
  {"name": "‏البحرين", "code": "BH", "iso3Code": "BHR", "dial_code": "+973", "minLength": "8", "maxLength": "8"},
  {"name": "Bangladesh", "code": "BD", "iso3Code": "BGD", "dial_code": "+880", "minLength": "10", "maxLength": "10"},
  {"name": "Barbados", "code": "BB", "iso3Code": "BRB", "dial_code": "+1246", "minLength": "7", "maxLength": "7"},
  {"name": "Белару́сь", "code": "BY", "iso3Code": "BLR", "dial_code": "+375", "minLength": "9", "maxLength": "10"},
  {"name": "België", "code": "BE", "iso3Code": "BEL", "dial_code": "+32", "minLength": "9", "maxLength": "9"},
  {"name": "Belize", "code": "BZ", "iso3Code": "BLZ", "dial_code": "+501", "minLength": "7", "maxLength": "7"},
  {"name": "Bénin", "code": "BJ", "iso3Code": "BEN", "dial_code": "+229", "minLength": "8", "maxLength": "8"},
  {"name": "Bermuda", "code": "BM", "iso3Code": "BMU", "dial_code": "+1441", "minLength": "7", "maxLength": "7"},
  {"name": "ʼbrug-yul", "code": "BT", "iso3Code": "BTN", "dial_code": "+975", "minLength": "8", "maxLength": "8"},
  {"name": "Bolivia", "code": "BO", "iso3Code": "BOL", "dial_code": "+591", "minLength": "8", "maxLength": "8"},
  {
    "name": "Bosna i Hercegovina",
    "code": "BA",
    "iso3Code": "BIH",
    "dial_code": "+387",
    "minLength": "9",
    "maxLength": "9"
  },
  {"name": "Botswana", "code": "BW", "iso3Code": "BWA", "dial_code": "+267", "minLength": "8", "maxLength": "8"},
  {"name": "Bouvetøya", "code": "BV", "iso3Code": "BVT", "dial_code": "+47", "minLength": "15", "maxLength": "15"},
  {"name": "Brasil", "code": "BR", "iso3Code": "BRA", "dial_code": "+55", "minLength": "11", "maxLength": "11"},
  {
    "name": "British Indian Ocean Territory",
    "code": "IO",
    "iso3Code": "IOT",
    "dial_code": "+246",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "Negara Brunei Darussalam",
    "code": "BN",
    "iso3Code": "BRN",
    "dial_code": "+673",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "България", "code": "BG", "iso3Code": "BGR", "dial_code": "+359", "minLength": "9", "maxLength": "9"},
  {"name": "Burkina Faso", "code": "BF", "iso3Code": "BFA", "dial_code": "+226", "minLength": "8", "maxLength": "8"},
  {"name": "Burundi", "code": "BI", "iso3Code": "BDI", "dial_code": "+257", "minLength": "8", "maxLength": "8"},
  {"name": "Cambodia", "code": "KH", "iso3Code": "KHM", "dial_code": "+855", "minLength": "9", "maxLength": "9"},
  {"name": "Cameroon", "code": "CM", "iso3Code": "CMR", "dial_code": "+237", "minLength": "9", "maxLength": "9"},
  {"name": "Canada", "code": "CA", "iso3Code": "CAN", "dial_code": "+1", "minLength": "10", "maxLength": "10"},
  {"name": "Cabo Verde", "code": "CV", "iso3Code": "CPV", "dial_code": "+238", "minLength": "7", "maxLength": "7"},
  {"name": "Cayman Islands", "code": "KY", "iso3Code": "CYM", "dial_code": "+1345", "minLength": "7", "maxLength": "7"},
  {
    "name": "Ködörösêse tî Bêafrîka",
    "code": "CF",
    "iso3Code": "CAF",
    "dial_code": "+236",
    "minLength": "8",
    "maxLength": "8"
  },
  {"name": "Tchad", "code": "TD", "iso3Code": "TCD", "dial_code": "+235", "minLength": "7", "maxLength": "7"},
  {"name": "Chile", "code": "CL", "iso3Code": "CHL", "dial_code": "+56", "minLength": "9", "maxLength": "9"},
  {"name": "中国", "code": "CN", "iso3Code": "CHN", "dial_code": "+86", "minLength": "11", "maxLength": "12"},
  {
    "name": "Christmas Island",
    "code": "CX",
    "iso3Code": "CXR",
    "dial_code": "+61",
    "minLength": "15",
    "maxLength": "15"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "code": "CC",
    "iso3Code": "CCK",
    "dial_code": "+61",
    "minLength": "15",
    "maxLength": "15"
  },
  {"name": "Colombia", "code": "CO", "iso3Code": "COL", "dial_code": "+57", "minLength": "10", "maxLength": "10"},
  {"name": "Komori", "code": "KM", "iso3Code": "COM", "dial_code": "+269", "minLength": "7", "maxLength": "7"},
  {
    "name": "République du Congo",
    "code": "CG",
    "iso3Code": "COG",
    "dial_code": "+242",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "République démocratique du Congo",
    "code": "CD",
    "iso3Code": "COD",
    "dial_code": "+243",
    "minLength": "9",
    "maxLength": "9"
  },
  {"name": "Cook Islands", "code": "CK", "iso3Code": "COK", "dial_code": "+682", "minLength": "5", "maxLength": "5"},
  {"name": "Costa Rica", "code": "CR", "iso3Code": "CRI", "dial_code": "+506", "minLength": "8", "maxLength": "8"},
  {"name": "Côte d'Ivoire", "code": "CI", "iso3Code": "CIV", "dial_code": "+225", "minLength": "10", "maxLength": "10"},
  {"name": "Hrvatska", "code": "HR", "iso3Code": "HRV", "dial_code": "+385", "minLength": "12", "maxLength": "12"},
  {"name": "Cuba", "code": "CU", "iso3Code": "CUB", "dial_code": "+53", "minLength": "8", "maxLength": "8"},
  {"name": "Κύπρος", "code": "CY", "iso3Code": "CYP", "dial_code": "+357", "minLength": "8", "maxLength": "8"},
  {"name": "Česká republika", "code": "CZ", "iso3Code": "CZE", "dial_code": "+420", "minLength": "9", "maxLength": "9"},
  {"name": "Danmark", "code": "DK", "iso3Code": "DNK", "dial_code": "+45", "minLength": "8", "maxLength": "8"},
  {"name": "Djibouti", "code": "DJ", "iso3Code": "DJI", "dial_code": "+253", "minLength": "6", "maxLength": "6"},
  {"name": "Dominica", "code": "DM", "iso3Code": "DMA", "dial_code": "+1767", "minLength": "7", "maxLength": "7"},
  {
    "name": "República Dominicana",
    "code": "DO",
    "iso3Code": "DOM",
    "dial_code": "+1",
    "minLength": "10",
    "maxLength": "10"
  },
  {"name": "Ecuador", "code": "EC", "iso3Code": "ECU", "dial_code": "+593", "minLength": "8", "maxLength": "9"},
  {"name": "مصر‎", "code": "EG", "iso3Code": "EGY", "dial_code": "+20", "minLength": "10", "maxLength": "10"},
  {"name": "El Salvador", "code": "SV", "iso3Code": "SLV", "dial_code": "+503", "minLength": "11", "maxLength": "11"},
  {
    "name": "Guinea Ecuatorial",
    "code": "GQ",
    "iso3Code": "GNQ",
    "dial_code": "+240",
    "minLength": "6",
    "maxLength": "6"
  },
  {"name": "ኤርትራ", "code": "ER", "iso3Code": "ERI", "dial_code": "+291", "minLength": "7", "maxLength": "7"},
  {"name": "Eesti", "code": "EE", "iso3Code": "EST", "dial_code": "+372", "minLength": "10", "maxLength": "10"},
  {"name": "ኢትዮጵያ", "code": "ET", "iso3Code": "ETH", "dial_code": "+251", "minLength": "9", "maxLength": "9"},
  {
    "name": "Falkland Islands",
    "code": "FK",
    "iso3Code": "FLK",
    "dial_code": "+500",
    "minLength": "5",
    "maxLength": "5"
  },
  {"name": "Føroyar", "code": "FO", "iso3Code": "FRO", "dial_code": "+298", "minLength": "6", "maxLength": "6"},
  {"name": "Fiji", "code": "FJ", "iso3Code": "FJI", "dial_code": "+679", "minLength": "7", "maxLength": "7"},
  {"name": "Suomi", "code": "FI", "iso3Code": "FIN", "dial_code": "+358", "minLength": "12", "maxLength": "12"},
  {"name": "France", "code": "FR", "iso3Code": "FRA", "dial_code": "+33", "minLength": "9", "maxLength": "9"},
  {
    "name": "Guyane française",
    "code": "GF",
    "iso3Code": "GUF",
    "dial_code": "+594",
    "minLength": "15",
    "maxLength": "15"
  },
  {
    "name": "Polynésie française",
    "code": "PF",
    "iso3Code": "PYF",
    "dial_code": "+689",
    "minLength": "6",
    "maxLength": "6"
  },
  {
    "name": "Territoire des Terres australes et antarctiques fr",
    "code": "TF",
    "iso3Code": "ATF",
    "dial_code": "+262",
    "minLength": "15",
    "maxLength": "15"
  },
  {"name": "Gabon", "code": "GA", "iso3Code": "GAB", "dial_code": "+241", "minLength": "9", "maxLength": "9"},
  {"name": "Gambia", "code": "GM", "iso3Code": "GMB", "dial_code": "+220", "minLength": "7", "maxLength": "7"},
  {"name": "საქართველო", "code": "GE", "iso3Code": "GEO", "dial_code": "+995", "minLength": "8", "maxLength": "9"},
  {"name": "Deutschland", "code": "DE", "iso3Code": "DEU", "dial_code": "+49", "minLength": "9", "maxLength": "13"},
  {"name": "Ghana", "code": "GH", "iso3Code": "GHA", "dial_code": "+233", "minLength": "9", "maxLength": "9"},
  {"name": "Gibraltar", "code": "GI", "iso3Code": "GIB", "dial_code": "+350", "minLength": "8", "maxLength": "8"},
  {"name": "Ελλάδα", "code": "GR", "iso3Code": "GRC", "dial_code": "+30", "minLength": "10", "maxLength": "10"},
  {
    "name": "Kalaallit Nunaat",
    "code": "GL",
    "iso3Code": "GRL",
    "dial_code": "+299",
    "minLength": "6",
    "maxLength": "6"
  },
  {"name": "Grenada", "code": "GD", "iso3Code": "GRD", "dial_code": "+1473", "minLength": "7", "maxLength": "7"},
  {"name": "Guadeloupe", "code": "GP", "iso3Code": "GLP", "dial_code": "+590", "minLength": "15", "maxLength": "15"},
  {"name": "Guam", "code": "GU", "iso3Code": "GUM", "dial_code": "+1671", "minLength": "7", "maxLength": "7"},
  {"name": "Guatemala", "code": "GT", "iso3Code": "GTM", "dial_code": "+502", "minLength": "8", "maxLength": "8"},
  {"name": "Guernsey", "code": "GG", "iso3Code": "GGY", "dial_code": "+44", "minLength": "6", "maxLength": "6"},
  {"name": "Guinée", "code": "GN", "iso3Code": "GIN", "dial_code": "+224", "minLength": "8", "maxLength": "9"},
  {"name": "Guiné-Bissau", "code": "GW", "iso3Code": "GNB", "dial_code": "+245", "minLength": "7", "maxLength": "7"},
  {"name": "Guyana", "code": "GY", "iso3Code": "GUY", "dial_code": "+592", "minLength": "7", "maxLength": "7"},
  {"name": "Haïti", "code": "HT", "iso3Code": "HTI", "dial_code": "+509", "minLength": "8", "maxLength": "8"},
  {
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "iso3Code": "HMD",
    "dial_code": "+0",
    "minLength": "15",
    "maxLength": "15"
  },
  {"name": "Vaticano", "code": "VA", "iso3Code": "VAT", "dial_code": "+379", "minLength": "10", "maxLength": "10"},
  {"name": "Honduras", "code": "HN", "iso3Code": "HND", "dial_code": "+504", "minLength": "8", "maxLength": "8"},
  {"name": "香港", "code": "HK", "iso3Code": "HKG", "dial_code": "+852", "minLength": "8", "maxLength": "8"},
  {"name": "Magyarország", "code": "HU", "iso3Code": "HUN", "dial_code": "+36", "minLength": "9", "maxLength": "9"},
  {"name": "Ísland", "code": "IS", "iso3Code": "ISL", "dial_code": "+354", "minLength": "7", "maxLength": "9"},
  {"name": "भारत", "code": "IN", "iso3Code": "IND", "dial_code": "+91", "minLength": "10", "maxLength": "10"},
  {"name": "Indonesia", "code": "ID", "iso3Code": "IDN", "dial_code": "+62", "minLength": "10", "maxLength": "13"},
  {"name": "ایران", "code": "IR", "iso3Code": "IRN", "dial_code": "+98", "minLength": "10", "maxLength": "10"},
  {"name": "العراق", "code": "IQ", "iso3Code": "IRQ", "dial_code": "+964", "minLength": "10", "maxLength": "10"},
  {"name": "Éire", "code": "IE", "iso3Code": "IRL", "dial_code": "+353", "minLength": "7", "maxLength": "9"},
  {"name": "Isle of Man", "code": "IM", "iso3Code": "IMN", "dial_code": "+44", "minLength": "6", "maxLength": "6"},
  {"name": "ישראל", "code": "IL", "iso3Code": "ISR", "dial_code": "+972", "minLength": "9", "maxLength": "9"},
  {"name": "Italia", "code": "IT", "iso3Code": "ITA", "dial_code": "+39", "minLength": "9", "maxLength": "10"},
  {"name": "Jamaica", "code": "JM", "iso3Code": "JAM", "dial_code": "+1876", "minLength": "7", "maxLength": "7"},
  {"name": "日本", "code": "JP", "iso3Code": "JPN", "dial_code": "+81", "minLength": "10", "maxLength": "10"},
  {"name": "Jersey", "code": "JE", "iso3Code": "JEY", "dial_code": "+44", "minLength": "6", "maxLength": "6"},
  {"name": "الأردن", "code": "JO", "iso3Code": "JOR", "dial_code": "+962", "minLength": "9", "maxLength": "9"},
  {"name": "Қазақстан", "code": "KZ", "iso3Code": "KAZ", "dial_code": "+7", "minLength": "10", "maxLength": "10"},
  {"name": "Kenya", "code": "KE", "iso3Code": "KEN", "dial_code": "+254", "minLength": "10", "maxLength": "10"},
  {"name": "Kiribati", "code": "KI", "iso3Code": "KIR", "dial_code": "+686", "minLength": "5", "maxLength": "5"},
  {"name": "북한", "code": "KP", "iso3Code": "PRK", "dial_code": "+850", "minLength": "10", "maxLength": "10"},
  {"name": "대한민국", "code": "KR", "iso3Code": "KOR", "dial_code": "+82", "minLength": "11", "maxLength": "11"},
  {
    "name": "Republika e Kosovës",
    "code": "XK",
    "iso3Code": "KOS",
    "dial_code": "+383",
    "minLength": "8",
    "maxLength": "8"
  },
  {"name": "الكويت", "code": "KW", "iso3Code": "KWT", "dial_code": "+965", "minLength": "8", "maxLength": "8"},
  {"name": "Кыргызстан", "code": "KG", "iso3Code": "KGZ", "dial_code": "+996", "minLength": "9", "maxLength": "9"},
  {"name": "ສປປລາວ", "code": "LA", "iso3Code": "LAO", "dial_code": "+856", "minLength": "10", "maxLength": "10"},
  {"name": "Latvija", "code": "LV", "iso3Code": "LVA", "dial_code": "+371", "minLength": "8", "maxLength": "8"},
  {"name": "لبنان", "code": "LB", "iso3Code": "LBN", "dial_code": "+961", "minLength": "8", "maxLength": "8"},
  {"name": "Lesotho", "code": "LS", "iso3Code": "LSO", "dial_code": "+266", "minLength": "8", "maxLength": "8"},
  {"name": "Liberia", "code": "LR", "iso3Code": "LBR", "dial_code": "+231", "minLength": "8", "maxLength": "8"},
  {"name": "‏ليبيا", "code": "LY", "iso3Code": "LBY", "dial_code": "+218", "minLength": "9", "maxLength": "9"},
  {"name": "Liechtenstein", "code": "LI", "iso3Code": "LIE", "dial_code": "+423", "minLength": "9", "maxLength": "9"},
  {"name": "Lietuva", "code": "LT", "iso3Code": "LTU", "dial_code": "+370", "minLength": "8", "maxLength": "8"},
  {"name": "Luxembourg", "code": "LU", "iso3Code": "LUX", "dial_code": "+352", "minLength": "11", "maxLength": "11"},
  {"name": "澳門", "code": "MO", "iso3Code": "MAC", "dial_code": "+853", "minLength": "8", "maxLength": "8"},
  {"name": "Македонија", "code": "MK", "iso3Code": "MKD", "dial_code": "+389", "minLength": "8", "maxLength": "8"},
  {"name": "Madagasikara", "code": "MG", "iso3Code": "MDG", "dial_code": "+261", "minLength": "10", "maxLength": "10"},
  {"name": "Malawi", "code": "MW", "iso3Code": "MWI", "dial_code": "+265", "minLength": "7", "maxLength": "9"},
  {"name": "Malaysia", "code": "MY", "iso3Code": "MYS", "dial_code": "+60", "minLength": "9", "maxLength": "10"},
  {"name": "Maldives", "code": "MV", "iso3Code": "MDV", "dial_code": "+960", "minLength": "7", "maxLength": "7"},
  {"name": "Mali", "code": "ML", "iso3Code": "MLI", "dial_code": "+223", "minLength": "8", "maxLength": "8"},
  {"name": "Malta", "code": "MT", "iso3Code": "MLT", "dial_code": "+356", "minLength": "8", "maxLength": "8"},
  {"name": "M̧ajeļ", "code": "MH", "iso3Code": "MHL", "dial_code": "+692", "minLength": "7", "maxLength": "7"},
  {"name": "Martinique", "code": "MQ", "iso3Code": "MTQ", "dial_code": "+596", "minLength": "15", "maxLength": "15"},
  {"name": "موريتانيا", "code": "MR", "iso3Code": "MRT", "dial_code": "+222", "minLength": "8", "maxLength": "8"},
  {"name": "Maurice", "code": "MU", "iso3Code": "MUS", "dial_code": "+230", "minLength": "7", "maxLength": "8"},
  {"name": "Mayotte", "code": "YT", "iso3Code": "MYT", "dial_code": "+262", "minLength": "9", "maxLength": "9"},
  {"name": "México", "code": "MX", "iso3Code": "MEX", "dial_code": "+52", "minLength": "10", "maxLength": "10"},
  {"name": "Micronesia", "code": "FM", "iso3Code": "FSM", "dial_code": "+691", "minLength": "7", "maxLength": "7"},
  {"name": "Moldova", "code": "MD", "iso3Code": "MDA", "dial_code": "+373", "minLength": "8", "maxLength": "8"},
  {"name": "Monaco", "code": "MC", "iso3Code": "MCO", "dial_code": "+377", "minLength": "9", "maxLength": "9"},
  {"name": "Монгол улс", "code": "MN", "iso3Code": "MNG", "dial_code": "+976", "minLength": "8", "maxLength": "8"},
  {"name": "Црна Гора", "code": "ME", "iso3Code": "MNE", "dial_code": "+382", "minLength": "12", "maxLength": "12"},
  {"name": "Montserrat", "code": "MS", "iso3Code": "MSR", "dial_code": "+1664", "minLength": "7", "maxLength": "7"},
  {"name": "المغرب", "code": "MA", "iso3Code": "MAR", "dial_code": "+212", "minLength": "9", "maxLength": "9"},
  {"name": "Moçambique", "code": "MZ", "iso3Code": "MOZ", "dial_code": "+258", "minLength": "9", "maxLength": "9"},
  {"name": "Myanmar", "code": "MM", "iso3Code": "MMR", "dial_code": "+95", "minLength": "9", "maxLength": "9"},
  {"name": "Namibia", "code": "NA", "iso3Code": "NAM", "dial_code": "+264", "minLength": "10", "maxLength": "10"},
  {"name": "Nauru", "code": "NR", "iso3Code": "NRU", "dial_code": "+674", "minLength": "7", "maxLength": "7"},
  {"name": "नेपाल", "code": "NP", "iso3Code": "NPL", "dial_code": "+977", "minLength": "10", "maxLength": "10"},
  {"name": "Nederland", "code": "NL", "iso3Code": "NLD", "dial_code": "+31", "minLength": "9", "maxLength": "9"},
  {
    "name": "Netherlands Antilles",
    "code": "AN",
    "iso3Code": "AN",
    "dial_code": "+599",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "Nouvelle-Calédonie",
    "code": "NC",
    "iso3Code": "NCL",
    "dial_code": "+687",
    "minLength": "6",
    "maxLength": "6"
  },
  {"name": "New Zealand", "code": "NZ", "iso3Code": "NZL", "dial_code": "+64", "minLength": "10", "maxLength": "10"},
  {"name": "Nicaragua", "code": "NI", "iso3Code": "NIC", "dial_code": "+505", "minLength": "8", "maxLength": "8"},
  {"name": "Niger", "code": "NE", "iso3Code": "NER", "dial_code": "+227", "minLength": "8", "maxLength": "8"},
  {"name": "Nigeria", "code": "NG", "iso3Code": "NGA", "dial_code": "+234", "minLength": "10", "maxLength": "11"},
  {"name": "Niuē", "code": "NU", "iso3Code": "NIU", "dial_code": "+683", "minLength": "4", "maxLength": "4"},
  {
    "name": "Norfolk Island",
    "code": "NF",
    "iso3Code": "NFK",
    "dial_code": "+672",
    "minLength": "15",
    "maxLength": "15"
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP",
    "iso3Code": "MNP",
    "dial_code": "+1670",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "Norge", "code": "NO", "iso3Code": "NOR", "dial_code": "+47", "minLength": "8", "maxLength": "8"},
  {"name": "عمان", "code": "OM", "iso3Code": "OMN", "dial_code": "+968", "minLength": "8", "maxLength": "8"},
  {"name": "Pakistan", "code": "PK", "iso3Code": "PAK", "dial_code": "+92", "minLength": "10", "maxLength": "10"},
  {"name": "Palau", "code": "PW", "iso3Code": "PLW", "dial_code": "+680", "minLength": "7", "maxLength": "7"},
  {"name": "فلسطين", "code": "PS", "iso3Code": "PSE", "dial_code": "+970", "minLength": "9", "maxLength": "9"},
  {"name": "Panamá", "code": "PA", "iso3Code": "PAN", "dial_code": "+507", "minLength": "8", "maxLength": "8"},
  {"name": "Papua Niugini", "code": "PG", "iso3Code": "PNG", "dial_code": "+675", "minLength": "11", "maxLength": "11"},
  {"name": "Paraguay", "code": "PY", "iso3Code": "PRY", "dial_code": "+595", "minLength": "10", "maxLength": "10"},
  {"name": "Perú", "code": "PE", "iso3Code": "PER", "dial_code": "+51", "minLength": "9", "maxLength": "9"},
  {"name": "Pilipinas", "code": "PH", "iso3Code": "PHL", "dial_code": "+63", "minLength": "10", "maxLength": "10"},
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "iso3Code": "PCN",
    "dial_code": "+64",
    "minLength": "10",
    "maxLength": "10"
  },
  {"name": "Polska", "code": "PL", "iso3Code": "POL", "dial_code": "+48", "minLength": "9", "maxLength": "9"},
  {"name": "Portugal", "code": "PT", "iso3Code": "PRT", "dial_code": "+351", "minLength": "9", "maxLength": "9"},
  {"name": "Puerto Rico", "code": "PR", "iso3Code": "PRI", "dial_code": "+1939", "minLength": "15", "maxLength": "15"},
  {"name": "Puerto Rico", "code": "PR", "iso3Code": "PRI", "dial_code": "+1787", "minLength": "15", "maxLength": "15"},
  {"name": "قطر", "code": "QA", "iso3Code": "QAT", "dial_code": "+974", "minLength": "8", "maxLength": "8"},
  {"name": "România", "code": "RO", "iso3Code": "ROU", "dial_code": "+40", "minLength": "9", "maxLength": "9"},
  {"name": "Россия", "code": "RU", "iso3Code": "RUS", "dial_code": "+7", "minLength": "10", "maxLength": "10"},
  {"name": "Rwanda", "code": "RW", "iso3Code": "RWA", "dial_code": "+250", "minLength": "9", "maxLength": "9"},
  {"name": "La Réunion", "code": "RE", "iso3Code": "REU", "dial_code": "+262", "minLength": "9", "maxLength": "9"},
  {
    "name": "Saint-Barthélemy",
    "code": "BL",
    "iso3Code": "BLM",
    "dial_code": "+590",
    "minLength": "9",
    "maxLength": "9"
  },
  {"name": "Saint Helena", "code": "SH", "iso3Code": "SHN", "dial_code": "+290", "minLength": "4", "maxLength": "4"},
  {
    "name": "Saint Kitts and Nevis",
    "code": "KN",
    "iso3Code": "KNA",
    "dial_code": "+1869",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "Saint Lucia", "code": "LC", "iso3Code": "LCA", "dial_code": "+1758", "minLength": "7", "maxLength": "7"},
  {"name": "Saint-Martin", "code": "MF", "iso3Code": "MAF", "dial_code": "+590", "minLength": "9", "maxLength": "9"},
  {
    "name": "Saint-Pierre-et-Miquelon",
    "code": "PM",
    "iso3Code": "SPM",
    "dial_code": "+508",
    "minLength": "6",
    "maxLength": "6"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "iso3Code": "VCT",
    "dial_code": "+1784",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "Samoa", "code": "WS", "iso3Code": "WSM", "dial_code": "+685", "minLength": "7", "maxLength": "7"},
  {"name": "San Marino", "code": "SM", "iso3Code": "SMR", "dial_code": "+378", "minLength": "10", "maxLength": "10"},
  {
    "name": "São Tomé e Príncipe",
    "code": "ST",
    "iso3Code": "STP",
    "dial_code": "+239",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "العربية السعودية",
    "code": "SA",
    "iso3Code": "SAU",
    "dial_code": "+966",
    "minLength": "9",
    "maxLength": "9"
  },
  {"name": "Sénégal", "code": "SN", "iso3Code": "SEN", "dial_code": "+221", "minLength": "9", "maxLength": "9"},
  {"name": "Србија", "code": "RS", "iso3Code": "SRB", "dial_code": "+381", "minLength": "12", "maxLength": "12"},
  {"name": "Seychelles", "code": "SC", "iso3Code": "SYC", "dial_code": "+248", "minLength": "6", "maxLength": "6"},
  {"name": "Sierra Leone", "code": "SL", "iso3Code": "SLE", "dial_code": "+232", "minLength": "8", "maxLength": "8"},
  {"name": "Singapore", "code": "SG", "iso3Code": "SGP", "dial_code": "+65", "minLength": "8", "maxLength": "8"},
  {"name": "Slovensko", "code": "SK", "iso3Code": "SVK", "dial_code": "+421", "minLength": "9", "maxLength": "9"},
  {"name": "Slovenija", "code": "SI", "iso3Code": "SVN", "dial_code": "+386", "minLength": "8", "maxLength": "8"},
  {"name": "Solomon Islands", "code": "SB", "iso3Code": "SLB", "dial_code": "+677", "minLength": "5", "maxLength": "5"},
  {"name": "Soomaaliya", "code": "SO", "iso3Code": "SOM", "dial_code": "+252", "minLength": "8", "maxLength": "8"},
  {"name": "South Africa", "code": "ZA", "iso3Code": "ZAF", "dial_code": "+27", "minLength": "9", "maxLength": "9"},
  {"name": "South Sudan", "code": "SS", "iso3Code": "SSD", "dial_code": "+211", "minLength": "9", "maxLength": "9"},
  {"name": "South Georgia", "code": "GS", "iso3Code": "SGS", "dial_code": "+500", "minLength": "15", "maxLength": "15"},
  {"name": "España", "code": "ES", "iso3Code": "ESP", "dial_code": "+34", "minLength": "9", "maxLength": "9"},
  {"name": "Sri Lanka", "code": "LK", "iso3Code": "LKA", "dial_code": "+94", "minLength": "9", "maxLength": "9"},
  {"name": "السودان", "code": "SD", "iso3Code": "SDN", "dial_code": "+249", "minLength": "9", "maxLength": "9"},
  {"name": "Suriname", "code": "SR", "iso3Code": "SUR", "dial_code": "+597", "minLength": "7", "maxLength": "7"},
  {
    "name": "Svalbard og Jan Mayen",
    "code": "SJ",
    "iso3Code": "SJM",
    "dial_code": "+47",
    "minLength": "8",
    "maxLength": "8"
  },
  {"name": "Swaziland", "code": "SZ", "iso3Code": "SWZ", "dial_code": "+268", "minLength": "8", "maxLength": "8"},
  {"name": "Sverige", "code": "SE", "iso3Code": "SWE", "dial_code": "+46", "minLength": "7", "maxLength": "13"},
  {"name": "Schweiz", "code": "CH", "iso3Code": "CHE", "dial_code": "+41", "minLength": "9", "maxLength": "12"},
  {"name": "سوريا", "code": "SY", "iso3Code": "SYR", "dial_code": "+963", "minLength": "9", "maxLength": "9"},
  {"name": "臺灣", "code": "TW", "iso3Code": "TWN", "dial_code": "+886", "minLength": "9", "maxLength": "9"},
  {"name": "Тоҷикистон", "code": "TJ", "iso3Code": "TJK", "dial_code": "+992", "minLength": "9", "maxLength": "9"},
  {"name": "Tanzania", "code": "TZ", "iso3Code": "TZA", "dial_code": "+255", "minLength": "9", "maxLength": "9"},
  {"name": "ประเทศไทย", "code": "TH", "iso3Code": "THA", "dial_code": "+66", "minLength": "9", "maxLength": "9"},
  {"name": "Timor-Leste", "code": "TL", "iso3Code": "TLS", "dial_code": "+670", "minLength": "7", "maxLength": "7"},
  {"name": "Togo", "code": "TG", "iso3Code": "TGO", "dial_code": "+228", "minLength": "8", "maxLength": "8"},
  {"name": "Tokelau", "code": "TK", "iso3Code": "TKL", "dial_code": "+690", "minLength": "4", "maxLength": "4"},
  {"name": "Tonga", "code": "TO", "iso3Code": "TON", "dial_code": "+676", "minLength": "7", "maxLength": "7"},
  {
    "name": "Trinidad and Tobago",
    "code": "TT",
    "iso3Code": "TTO",
    "dial_code": "+1868",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "تونس", "code": "TN", "iso3Code": "TUN", "dial_code": "+216", "minLength": "8", "maxLength": "8"},
  {"name": "Türkiye", "code": "TR", "iso3Code": "TUR", "dial_code": "+90", "minLength": "10", "maxLength": "10"},
  {"name": "Türkmenistan", "code": "TM", "iso3Code": "TKM", "dial_code": "+993", "minLength": "8", "maxLength": "8"},
  {
    "name": "Turks and Caicos Islands",
    "code": "TC",
    "iso3Code": "TCA",
    "dial_code": "+1649",
    "minLength": "7",
    "maxLength": "7"
  },
  {"name": "Tuvalu", "code": "TV", "iso3Code": "TUV", "dial_code": "+688", "minLength": "6", "maxLength": "6"},
  {"name": "Uganda", "code": "UG", "iso3Code": "UGA", "dial_code": "+256", "minLength": "9", "maxLength": "9"},
  {"name": "Україна", "code": "UA", "iso3Code": "UKR", "dial_code": "+380", "minLength": "9", "maxLength": "9"},
  {
    "name": "دولة الإمارات العربية المتحدة",
    "code": "AE",
    "iso3Code": "ARE",
    "dial_code": "+971",
    "minLength": "9",
    "maxLength": "9"
  },
  {"name": "United Kingdom", "code": "GB", "iso3Code": "GBR", "dial_code": "+44", "minLength": "10", "maxLength": "10"},
  {"name": "United States", "code": "US", "iso3Code": "USA", "dial_code": "+1", "minLength": "10", "maxLength": "10"},
  {"name": "Uruguay", "code": "UY", "iso3Code": "URY", "dial_code": "+598", "minLength": "9", "maxLength": "9"},
  {"name": "O'zbekiston", "code": "UZ", "iso3Code": "UZB", "dial_code": "+998", "minLength": "9", "maxLength": "9"},
  {"name": "Vanuatu", "code": "VU", "iso3Code": "VUT", "dial_code": "+678", "minLength": "7", "maxLength": "7"},
  {"name": "Venezuela", "code": "VE", "iso3Code": "VEN", "dial_code": "+58", "minLength": "10", "maxLength": "10"},
  {"name": "Việt Nam", "code": "VN", "iso3Code": "VNM", "dial_code": "+84", "minLength": "11", "maxLength": "11"},
  {
    "name": "British Virgin Islands",
    "code": "VG",
    "iso3Code": "VGB",
    "dial_code": "+1284",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "United States Virgin Islands",
    "code": "VI",
    "iso3Code": "VIR",
    "dial_code": "+1340",
    "minLength": "7",
    "maxLength": "7"
  },
  {
    "name": "Wallis et Futuna",
    "code": "WF",
    "iso3Code": "WLF",
    "dial_code": "+681",
    "minLength": "6",
    "maxLength": "6"
  },
  {"name": "اليَمَن", "code": "YE", "iso3Code": "YEM", "dial_code": "+967", "minLength": "9", "maxLength": "9"},
  {"name": "Zambia", "code": "ZM", "iso3Code": "ZMB", "dial_code": "+260", "minLength": "9", "maxLength": "9"},
  {"name": "Zimbabwe", "code": "ZW", "iso3Code": "ZWE", "dial_code": "+263", "minLength": "9", "maxLength": "9"}
];
